### ISSUE TITLE
Value of items not correct?

### ISSUE THREAD

**Issue by GormanV** [nofatigue/runelite-profit-tracker#3]
Hi,

I've tried out the plugin, seems like a really good idea and I'm glad it's on RL.

I noticed picking up loot @ brutal black dragons the value seemed off. 118k of dragon dart tips only pulled in a few thousand GP for example. Is this intentional?

**Comment by nofatigue** [comment]
Hey, you mean at the animation or actually in the profit calculation?

**Comment by GormanV** [comment]
The overlay box itself was showing 70kish profit (includes other loot). The gold "drops" that appear can't be read as the icon is over them, but that might be a font issue on my side? 

It doesn't change when I use up bolts or potions either, I assumed thats just how it works

**Comment by nofatigue** [comment]
Ok so the bug is (apart from font issue):
bolts / arrows fired aren't taken into calculation, aswell as arrows picked up when you  have arrows equiped.

**Comment by nofatigue** [comment]
About the potions: It doesn't reproduce for me in strength potions - I drink and and profit goes down, how do you use potions?

**Comment by GormanV** [comment]
Ah sorry, when I mentioned the dragon darts those are dart tips (I'm using diamond (e)bolts), basically unfinished stuff so I don't think it's related to "ammunition" as I can't equip those.

I'm using prayer pots, extended anti-fires and divine ranging pot. Didn't see any reduction when drinking those normally.

**Comment by nofatigue** [comment]
OK I see what you mean, it's range related I think

**Comment by nofatigue** [comment]
Yup. Melee works fine for me, ranged completely broken.

**Comment by nofatigue** [comment]
> Hi,
> 
> I've tried out the plugin, seems like a really good idea and I'm glad it's on RL.
> 
> I noticed picking up loot @ brutal black dragons the value seemed off. 118k of dragon dart tips only pulled in a few thousand GP for example. Is this intentional?

Hey, I've uploaded a fix for ranged. I think it should fix this bug. The new version should have an update in the GUI, (showing elapsed time).

**Comment by GormanV** [comment]
> > Hi,
> > I've tried out the plugin, seems like a really good idea and I'm glad it's on RL.
> > I noticed picking up loot @ brutal black dragons the value seemed off. 118k of dragon dart tips only pulled in a few thousand GP for example. Is this intentional?
> 
> Hey, I've uploaded a fix for ranged. I think it should fix this bug. The new version should have an update in the GUI, (showing elapsed time).

Great I'll try that out later today, thanks for sorting that!
